// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package adder

import (
	"context"

	goUUID "github.com/google/uuid"
	json "github.com/seniorGolang/json"
)

type ClientAdder struct {
	*ClientJsonRPC
}

type retAdderSumTwoNumbers func(result int, err error)

func (cli *ClientAdder) ReqSumTwoNumbers(ret retAdderSumTwoNumbers, first int, second int) (request baseJsonRPC) {

	request = baseJsonRPC{
		Method: "adder.sumtwonumbers",
		Params: requestAdderSumTwoNumbers{
			First:  first,
			Second: second,
		},
		Version: Version,
	}
	var err error
	var response responseAdderSumTwoNumbers

	if ret != nil {
		request.retHandler = func(jsonrpcResponse baseJsonRPC) {
			if jsonrpcResponse.Error != nil {
				err = cli.errorDecoder(jsonrpcResponse.Error)
				ret(response.Result, err)
				return
			}
			err = json.Unmarshal(jsonrpcResponse.Result, &response)
			ret(response.Result, err)
		}
		request.ID = []byte("\"" + goUUID.New().String() + "\"")
	}
	return
}

func (cli *ClientAdder) SumTwoNumbers(ctx context.Context, first int, second int) (result int, err error) {

	retHandler := func(_result int, _err error) {
		result = _result
		err = _err
	}
	if blockErr := cli.Batch(ctx, cli.ReqSumTwoNumbers(retHandler, first, second)); blockErr != nil {
		err = blockErr
		return
	}
	return
}
