// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package adder

type requestAdderSumTwoNumbers struct {
	First  int `json:"first"`
	Second int `json:"second"`
}

type responseAdderSumTwoNumbers struct {
	Result int `json:"result"`
}
