// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sergejkoll/tg-example/pkg/interfaces"
)

type AdderSumTwoNumbers func(ctx context.Context, first int, second int) (result int, err error)

type MiddlewareAdder func(next interfaces.Adder) interfaces.Adder

type MiddlewareAdderSumTwoNumbers func(next AdderSumTwoNumbers) AdderSumTwoNumbers
